name: Verify

on:
  pull_request:
    branches: [main]

# Cancel in-progress workflows for the same PR or branch/tag
concurrency:
  group: ${{ github.workflow }}-${{ github.event.pull_request.number || github.ref }}
  cancel-in-progress: true

# Needs to be a superset of what Verify workflow needs
permissions:
  contents:      read  # Clone repo
  id-token:      write # OIDC

jobs:
  build:
    timeout-minutes: 10
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: ./.github/actions/build
        with:
          dockerfile: ./Dockerfile
          context: .
